// src/components/Education.jsx
import { GraduationCap, Award, CheckCircle2, Compass, LayoutGrid } from 'lucide-react';
import { Reveal, Stagger, StaggerItem } from './motion/primitives';

const degrees = [
  {
    id: 0,
    years: '2019 - 2025',
    title: { en: 'Mechanical Engineering', de: 'Maschinenbau' },
    institution: 'FH Aachen University of Applied Sciences',
    description: {
      en: 'Mechanical Engineering degree with a focus on innovative mechanical solutions and sustainable technologies.',
      de: 'Maschinenbau-Studium mit Fokus auf innovative mechanische Lösungen und nachhaltige Technologien.',
    },
    tags: [
      { en: 'Engineering', de: 'Ingenieurwesen' },
      { en: 'Design', de: 'Design' },
      { en: 'Innovation', de: 'Innovation' },
    ],
  },
  {
    id: 1,
    years: '2018 - 2019',
    title: { en: 'German Language, Math & Physics', de: 'Deutsch, Mathematik & Physik' },
    institution: 'FH Aachen University of Applied Sciences',
    description: {
      en: 'Completed preparatory coursework for international students, focusing on German language skills, mathematics, and physics for engineering studies.',
      de: 'Absolvierter Vorbereitungskurs für internationale Studierende mit Schwerpunkt Deutsch, Mathematik und Physik für das Ingenieurstudium.',
    },
    tags: [
      { en: 'German Language', de: 'Deutsch' },
      { en: 'Mathematics', de: 'Mathematik' },
      { en: 'Physics', de: 'Physik' },
    ],
  },
  {
    id: 2,
    years: '2011 - 2018',
    title: { en: 'Math and Physics', de: 'Mathematik und Physik' },
    institution: 'National Organization for Development of Exceptional Talents (Sampad)',
    description: {
      en: 'Graduated from a specialized high school for gifted students with a focus on mathematics and physics.',
      de: 'Abschluss an einer spezialisierten Schule für hochbegabte Schüler mit Fokus auf Mathematik und Physik.',
    },
    tags: [
      { en: 'Mathematics', de: 'Mathematik' },
      { en: 'Physics', de: 'Physik' },
      { en: 'Advanced Studies', de: 'Vertiefte Studien' },
    ],
  },
];

const certifications = [
  {
    id: 0,
    icon: CheckCircle2,
    title: { en: 'Blockchain Basics', de: 'Blockchain Grundlagen' },
    kind: { en: 'Certification', de: 'Zertifizierung' },
    description: {
      en: 'Comprehensive certification in blockchain fundamentals, covering distributed ledger technology and smart contracts.',
      de: 'Umfassende Zertifizierung zu Blockchain-Grundlagen, inklusive Distributed-Ledger-Technologie und Smart Contracts.',
    },
  },
  {
    id: 1,
    icon: Compass,
    title: { en: 'Design Thinking Summer School', de: 'Design Thinking Summer School' },
    kind: { en: 'Certificate', de: 'Zertifikat' },
    description: {
      en: 'Intensive training in design thinking methodologies and user-centered design approaches for innovation.',
      de: 'Intensives Training in Design-Thinking-Methoden und nutzerzentrierten Innovationsansätzen.',
    },
  },
  {
    id: 2,
    icon: LayoutGrid,
    title: { en: 'Summer School Sustainable Entrepreneurship', de: 'Summer School Nachhaltiges Unternehmertum' },
    kind: { en: 'For Climate Action', de: 'Für Klimaschutz' },
    description: {
      en: 'Training in developing sustainable business models and ventures focused on addressing climate change.',
      de: 'Training zur Entwicklung nachhaltiger Geschäftsmodelle und Projekte mit Fokus auf Klimawandel.',
    },
  },
];

export default function Education({ language }) {
  return (
    <section id="education" className="py-24 md:py-32 px-6 bg-neutral-50">
      <div className="max-w-6xl mx-auto">
        <Reveal className="flex flex-col md:flex-row md:justify-between md:items-end mb-14">
          <div>
            <h2 className="font-display text-3xl md:text-4xl font-semibold tracking-tight text-ink">
              {language === 'de' ? 'Bildung' : 'Education'}
            </h2>
            <div className="w-16 h-1 bg-primary mt-3 rounded-full"></div>
          </div>
          <p className="text-sm text-neutral-500 mt-4 md:mt-0 md:text-right font-medium tracking-wide">
            {language === 'de' ? 'AKADEMISCHER HINTERGRUND' : 'ACADEMIC BACKGROUND'}
          </p>
        </Reveal>

        {/* Degrees: light list style */}
        <Stagger className="space-y-4 max-w-4xl">
          {degrees.map((degree) => (
            <StaggerItem
              key={degree.id}
              className="flex flex-col sm:flex-row gap-4 sm:gap-6 bg-white rounded-xl border border-neutral-200 p-6"
            >
              <div className="flex items-center gap-3 sm:flex-col sm:items-start sm:w-36 shrink-0">
                <div className="w-10 h-10 rounded-lg bg-accent/10 flex items-center justify-center shrink-0">
                  <GraduationCap className="w-5 h-5 text-accent" strokeWidth={1.5} />
                </div>
                <span className="text-sm font-semibold text-neutral-500">{degree.years}</span>
              </div>

              <div className="flex-1">
                <h3 className="text-xl font-semibold text-ink">{degree.title[language]}</h3>
                <div className="text-sm text-neutral-500 mt-0.5">{degree.institution}</div>
                <p className="text-sm text-neutral-700 leading-relaxed mt-3">
                  {degree.description[language]}
                </p>
                <div className="flex flex-wrap gap-2 mt-4">
                  {degree.tags.map((tag) => (
                    <span key={tag.en} className="text-xs font-medium text-neutral-600 bg-neutral-100 border border-neutral-200 rounded-full px-2.5 py-1">
                      {tag[language]}
                    </span>
                  ))}
                </div>
              </div>
            </StaggerItem>
          ))}
        </Stagger>

        {/* Certifications */}
        <div className="mt-16 max-w-6xl">
          <Reveal as="h3" className="text-xl font-semibold text-ink mb-6 flex items-center gap-2">
            <Award className="w-5 h-5 text-primary" strokeWidth={1.5} />
            {language === 'de' ? 'Zertifikate' : 'Certifications'}
          </Reveal>

          <Stagger className="grid md:grid-cols-3 gap-4">
            {certifications.map((cert) => {
              const Icon = cert.icon;
              return (
                <StaggerItem key={cert.id} className="bg-white p-5 rounded-xl border border-neutral-200">
                  <div className="flex items-center mb-3">
                    <div className="w-9 h-9 rounded-full bg-neutral-100 flex items-center justify-center mr-3 shrink-0">
                      <Icon className="w-4.5 h-4.5 text-neutral-600" strokeWidth={1.5} />
                    </div>
                    <div>
                      <h4 className="text-sm font-semibold text-ink leading-snug">{cert.title[language]}</h4>
                      <p className="text-xs text-neutral-500">{cert.kind[language]}</p>
                    </div>
                  </div>
                  <p className="text-sm text-neutral-600 leading-relaxed">
                    {cert.description[language]}
                  </p>
                </StaggerItem>
              );
            })}
          </Stagger>
        </div>
      </div>
    </section>
  );
}

// src/components/Education.vue
<template>
  <section id="education" class="py-20 px-6 bg-gradient-to-br from-teal-50/70 via-cyan-50/40 to-white">
    <div class="container mx-auto">
      <div class="flex flex-col md:flex-row md:justify-between md:items-end mb-12">
        <div>
          <h2 class="text-3xl font-bold mb-2 text-gray-800">{{ language === 'de' ? 'Bildung' : 'Education' }}</h2>
          <div class="w-24 h-1 bg-teal-600"></div>
        </div>
        <p class="text-gray-500 mt-4 md:mt-0 md:text-right text-sm font-medium">
          {{ language === 'de' ? 'AKADEMISCHER HINTERGRUND' : 'ACADEMIC BACKGROUND' }}
        </p>
      </div>
      
      <div class="space-y-12">
        <!-- Degree 1 -->
        <div class="bg-white/70 backdrop-blur-sm rounded-xl shadow-sm overflow-hidden border border-white/60">
          <div class="md:flex">
            <div class="md:w-1/3 bg-gradient-to-br from-teal-700 to-cyan-700 text-white p-6 flex flex-col justify-center items-center">
              <div class="text-2xl font-bold">2019 - 2025</div>
              <div class="text-teal-100 mt-2">{{ language === 'de' ? 'Maschinenbau' : 'Mechanical Engineering' }}</div>
              <div class="mt-4 p-2 bg-white/10 backdrop-blur-sm rounded-lg w-16 h-16 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.697 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5" />
                </svg>
              </div>
            </div>
            
            <div class="md:w-2/3 p-6">
              <div class="flex flex-col md:flex-row justify-between items-start">
                <div>
                  <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Maschinenbau' : 'Mechanical Engineering' }}</h3>
                  <div class="text-lg text-teal-600 font-medium mt-1">FH Aachen University of Applied Sciences</div>
                </div>
              </div>
              
              <div class="mt-4">
                <p class="text-gray-700">
                  {{ language === 'de' ? 'Maschinenbau-Studium mit Fokus auf innovative mechanische Loesungen und nachhaltige Technologien.' : 'Mechanical Engineering degree with a focus on innovative mechanical solutions and sustainable technologies.' }}
                </p>
              </div>
              
              <div class="mt-4 flex flex-wrap gap-2">
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Ingenieurwesen' : 'Engineering' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Design' : 'Design' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Innovation' : 'Innovation' }}</div>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Degree 2 -->
        <div class="bg-white/70 backdrop-blur-sm rounded-xl shadow-sm overflow-hidden border border-white/60">
          <div class="md:flex">
            <div class="md:w-1/3 bg-gradient-to-br from-teal-700 to-cyan-700 text-white p-6 flex flex-col justify-center items-center">
              <div class="text-2xl font-bold">2018 - 2019</div>
              <div class="text-teal-100 mt-2">{{ language === 'de' ? 'Freshman Institute' : 'Freshman Institute' }}</div>
              <div class="mt-4 p-2 bg-white/10 backdrop-blur-sm rounded-lg w-16 h-16 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.697 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5" />
                </svg>
              </div>
            </div>
            
            <div class="md:w-2/3 p-6">
              <div class="flex flex-col md:flex-row justify-between items-start">
                <div>
                  <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Deutsch, Mathematik & Physik' : 'German Language, Math & Physics' }}</h3>
                  <div class="text-lg text-teal-600 font-medium mt-1">FH Aachen University of Applied Sciences</div>
                </div>
              </div>
              
              <div class="mt-4">
                <p class="text-gray-700">
                  {{ language === 'de' ? 'Absolvierter Vorbereitungskurs fuer internationale Studierende mit Schwerpunkt Deutsch, Mathematik und Physik fuer das Ingenieurstudium.' : 'Completed preparatory coursework for international students, focusing on German language skills, mathematics, and physics for engineering studies.' }}
                </p>
              </div>
              
              <div class="mt-4 flex flex-wrap gap-2">
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Deutsch' : 'German Language' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Mathematik' : 'Mathematics' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Physik' : 'Physics' }}</div>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Degree 3 -->
        <div class="bg-white/70 backdrop-blur-sm rounded-xl shadow-sm overflow-hidden border border-white/60">
          <div class="md:flex">
            <div class="md:w-1/3 bg-gradient-to-br from-teal-700 to-cyan-700 text-white p-6 flex flex-col justify-center items-center">
              <div class="text-2xl font-bold">2011 - 2018</div>
              <div class="text-teal-100 mt-2">{{ language === 'de' ? 'Abitur' : 'High School Diploma' }}</div>
              <div class="mt-4 p-2 bg-white/10 backdrop-blur-sm rounded-lg w-16 h-16 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-10 h-10">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.697 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5" />
                </svg>
              </div>
            </div>
            
            <div class="md:w-2/3 p-6">
              <div class="flex flex-col md:flex-row justify-between items-start">
                <div>
                  <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Mathematik und Physik' : 'Math and Physics' }}</h3>
                  <div class="text-lg text-teal-600 font-medium mt-1">National Organization for Development of Exceptional Talents (Sampad)</div>
                </div>
              </div>
              
              <div class="mt-4">
                <p class="text-gray-700">
                  {{ language === 'de' ? 'Abschluss an einer spezialisierten Schule fuer hochbegabte Schueler mit Fokus auf Mathematik und Physik.' : 'Graduated from a specialized high school for gifted students with a focus on mathematics and physics.' }}
                </p>
              </div>
              
              <div class="mt-4 flex flex-wrap gap-2">
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Mathematik' : 'Mathematics' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Physik' : 'Physics' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 px-2.5 py-1 rounded-full text-xs font-medium">{{ language === 'de' ? 'Vertiefte Studien' : 'Advanced Studies' }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Certifications -->
      <div class="mt-16">
        <h3 class="text-2xl font-bold text-gray-800 mb-8 flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2 text-teal-600">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" />
          </svg>
          {{ language === 'de' ? 'Zertifikate' : 'Certifications' }}
        </h3>
        
        <div class="grid md:grid-cols-3 gap-6">
          <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
            <div class="flex items-center mb-4">
              <div class="w-12 h-12 rounded-full bg-amber-100 flex items-center justify-center mr-4 text-amber-600">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 01-1.043 3.296 3.745 3.745 0 01-3.296 1.043A3.745 3.745 0 0112 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 01-3.296-1.043 3.745 3.745 0 01-1.043-3.296A3.745 3.745 0 013 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 011.043-3.296 3.746 3.746 0 013.296-1.043A3.746 3.746 0 0112 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 013.296 1.043 3.746 3.746 0 011.043 3.296A3.745 3.745 0 0121 12z" />
                </svg>
              </div>
              <div>
                <h4 class="text-lg font-semibold text-gray-800">{{ language === 'de' ? 'Blockchain Grundlagen' : 'Blockchain Basics' }}</h4>
                <p class="text-gray-600">{{ language === 'de' ? 'Zertifizierung' : 'Certification' }}</p>
              </div>
            </div>
            <p class="text-gray-600 mt-2">
              {{ language === 'de' ? 'Umfassende Zertifizierung zu Blockchain-Grundlagen, inklusive Distributed-Ledger-Technologie und Smart Contracts.' : 'Comprehensive certification in blockchain fundamentals, covering distributed ledger technology and smart contracts.' }}
            </p>
          </div>
          
          <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
            <div class="flex items-center mb-4">
              <div class="w-12 h-12 rounded-full bg-emerald-500/10 border border-emerald-200/50 flex items-center justify-center mr-4 text-emerald-600">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23-.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
                </svg>
              </div>
              <div>
                <h4 class="text-lg font-semibold text-gray-800">{{ language === 'de' ? 'Design Thinking Summer School' : 'Design Thinking Summer School' }}</h4>
                <p class="text-gray-600">{{ language === 'de' ? 'Zertifikat' : 'Certificate' }}</p>
              </div>
            </div>
            <p class="text-gray-600 mt-2">
              {{ language === 'de' ? 'Intensives Training in Design-Thinking-Methoden und nutzerzentrierten Innovationsansaetzen.' : 'Intensive training in design thinking methodologies and user-centered design approaches for innovation.' }}
            </p>
          </div>
          
          <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
            <div class="flex items-center mb-4">
              <div class="w-12 h-12 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-4 text-teal-600">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21" />
                </svg>
              </div>
              <div>
                <h4 class="text-lg font-semibold text-gray-800">{{ language === 'de' ? 'Summer School Nachhaltiges Unternehmertum' : 'Summer School Sustainable Entrepreneurship' }}</h4>
                <p class="text-gray-600">{{ language === 'de' ? 'Fuer Klimaschutz' : 'For Climate Action' }}</p>
              </div>
            </div>
            <p class="text-gray-600 mt-2">
              {{ language === 'de' ? 'Training zur Entwicklung nachhaltiger Geschaeftsmodelle und Projekte mit Fokus auf Klimawandel.' : 'Training in developing sustainable business models and ventures focused on addressing climate change.' }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
defineProps({
  language: {
    type: String,
    default: 'en'
  }
});
</script>
