// src/components/Experience.vue
<template>
  <section id="experience" class="py-20 px-6 bg-gradient-to-br from-slate-50 via-teal-50/30 to-cyan-50/40">
    <div class="container mx-auto">

      <!-- Section header -->
      <div class="flex flex-col md:flex-row md:justify-between md:items-end mb-12">
        <div>
          <h2 class="text-3xl font-bold mb-2 text-gray-800">
            {{ language === 'de' ? 'Berufserfahrung' : 'Professional Experience' }}
          </h2>
          <div class="w-24 h-1 bg-teal-600"></div>
        </div>
        <p class="text-gray-500 mt-4 md:mt-0 md:text-right text-sm font-medium">
          {{ language === 'de' ? 'LUECKEN IDENTIFIZIERT. SYSTEME GEBAUT. ERGEBNISSE GELIEFERT.' : 'GAPS IDENTIFIED. SYSTEMS BUILT. RESULTS SHIPPED.' }}
        </p>
      </div>

      <!-- Timeline -->
      <div class="relative max-w-4xl mx-auto">
        <!-- Vertical line -->
        <div class="absolute left-5 top-2 bottom-2 w-px bg-gradient-to-b from-teal-400 via-teal-300 to-gray-200"></div>

        <div class="space-y-8">

          <!-- ── Role 01 — Current ── -->
          <div class="role-entry" ref="el0">
            <!-- Dot -->
            <div class="absolute left-0 w-10 h-10 rounded-full bg-gradient-to-br from-teal-500 to-cyan-500 flex items-center justify-center shadow-md shadow-teal-200 z-10">
              <span class="w-2.5 h-2.5 rounded-full bg-white animate-pulse"></span>
            </div>

            <!-- Card -->
            <div class="ml-16 bg-white rounded-2xl border border-teal-100 shadow-sm hover:shadow-md transition-shadow duration-300 overflow-hidden">
              <!-- Top accent -->
              <div class="h-1 bg-gradient-to-r from-teal-500 to-cyan-400"></div>
              <div class="p-6">
                <div class="flex flex-wrap items-start justify-between gap-2 mb-3">
                  <div>
                    <h3 class="text-lg font-bold text-gray-900">{{ language === 'de' ? 'Ecosystem & Product Builder' : 'Ecosystem & Product Builder' }}</h3>
                    <p class="text-sm text-teal-600 font-medium mt-0.5">growthepie / orbal GmbH · Remote</p>
                  </div>
                  <div class="flex items-center gap-2 shrink-0">
                    <span class="flex items-center gap-1.5 text-xs font-semibold text-teal-700 bg-teal-50 border border-teal-200 px-3 py-1 rounded-full">
                      <span class="w-1.5 h-1.5 rounded-full bg-teal-500 animate-pulse"></span>
                      {{ language === 'de' ? 'Aktuell' : 'Current' }}
                    </span>
                    <span class="text-xs text-gray-400 font-medium">Aug 2024 – {{ language === 'de' ? 'Heute' : 'Present' }}</span>
                  </div>
                </div>

                <ul class="space-y-2">
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'KI Labeling Agent' : 'AI labeling agent, and RL Pipelines' }}</strong> — {{ language === 'de' ? '€1→€0,01/Label, 4h→10min (100×)' : '€1→€0.01/label, 4h→10min (100×)' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'KI Sales Engine' : 'AI sales engine for research backed outreach and lead tracking' }}</strong> — {{ language === 'de' ? '30 simultane Gespraeche, 1h→10min pro Kontakt' : '30 simultaneous conversations, 1h→10min per contact' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? '3 Grant · $50,000' : '3 grants secured and shipped · $50,000' }}</strong> — EF ESP DevTooling, Gitcoin GG25 OSS Developer Tooling & Infra, Arbitrum Questbook Dev Tooling</li>
                  <li class="role-bullet"><strong class="role-kw">Open Labels Initiative</strong> — {{ language === 'de' ? 'TypeScript SDK, Hardhat Plugin, Web-Frontend; adoptiert von Blockscout, Enscribe, Sourcify' : 'TypeScript SDK, Hardhat plugin, web frontend; adopted by Blockscout, Enscribe, Sourcify' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'L2 Ecosystem Research' : 'L2 ecosystem research' }}</strong> — {{ language === 'de' ? 'Metriken & Insights; Protokolle & Daten-Teams' : 'metrics & insights; protocols & data teams' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'Frontend' : 'Frontend Development and Tools Integrations' }}</strong> — {{ language === 'de' ? 'Forschung in Produkt-Interfaces ueberfuehrt' : 'Turned hard dev tasks into intuitive user input agentic flows' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'KI Advocate' : 'Internal AI advocate' }}</strong> — {{ language === 'de' ? 'Tools, Workflows & Agenten: Engineering, Research, Produkt' : 'tools, workflows & agents across engineering, research, product' }}</li>
                </ul>

                <div class="flex flex-wrap gap-2 mt-4">
                  <span class="tag">TypeScript</span>
                  <span class="tag">Blockchain</span>
                  <span class="tag">AI Agents</span>
                  <span class="tag">Grants</span>
                  <span class="tag">Open Source</span>
                  <span class="tag">Product</span>
                </div>
              </div>
            </div>
          </div>

          <!-- ── Role 02 — Community & Growth ── -->
          <div class="role-entry" ref="el1">
            <div class="absolute left-0 w-10 h-10 rounded-full bg-white border-2 border-teal-300 flex items-center justify-center z-10">
              <span class="w-2 h-2 rounded-full bg-teal-400"></span>
            </div>
            <div class="ml-16 bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-300 overflow-hidden">
              <div class="h-1 bg-gradient-to-r from-gray-200 to-teal-200"></div>
              <div class="p-6">
                <div class="flex flex-wrap items-start justify-between gap-2 mb-3">
                  <div>
                    <h3 class="text-lg font-bold text-gray-900">{{ language === 'de' ? 'Community & Growth Manager' : 'Community & Growth Manager' }}</h3>
                    <p class="text-sm text-gray-500 font-medium mt-0.5">growthepie · Remote</p>
                  </div>
                  <span class="text-xs text-gray-400 font-medium shrink-0">Jun 2023 – Jul 2024</span>
                </div>

                <ul class="space-y-2">
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'Community Management' : 'Community management' }}</strong> — {{ language === 'de' ? 'Web3-Entwickler & Researcher; Blockchain-Analytics-Awareness' : 'Web3 developers & researchers; blockchain analytics awareness' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'Content Strategie' : 'Content strategy' }}</strong> — {{ language === 'de' ? 'On-Chain-Daten in zugaengliche Narrative uebersetzt' : 'on-chain data translated into accessible narratives' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'Sales & Partnerschaften' : 'Sales & partnerships' }}</strong> — {{ language === 'de' ? 'Protokoll-Beziehungen; Beitrag zur Wachstums-Engine' : 'protocol relationships; contribution to growth engine' }}</li>
                </ul>

                <div class="flex flex-wrap gap-2 mt-4">
                  <span class="tag">Community</span>
                  <span class="tag">Content Strategy</span>
                  <span class="tag">Web3</span>
                  <span class="tag">Sales</span>
                </div>
              </div>
            </div>
          </div>

          <!-- ── Role 03 — Design Thinking ── -->
          <div class="role-entry" ref="el2">
            <div class="absolute left-0 w-10 h-10 rounded-full bg-white border-2 border-gray-200 flex items-center justify-center z-10">
              <span class="w-2 h-2 rounded-full bg-gray-300"></span>
            </div>
            <div class="ml-16 bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow duration-300 overflow-hidden">
              <div class="h-1 bg-gradient-to-r from-gray-100 to-gray-200"></div>
              <div class="p-6">
                <div class="flex flex-wrap items-start justify-between gap-2 mb-3">
                  <div>
                    <h3 class="text-lg font-bold text-gray-900">{{ language === 'de' ? 'Design Thinking Coach & Studentische Hilfskraft' : 'Design Thinking Coach & Student Assistant' }}</h3>
                    <p class="text-sm text-gray-500 font-medium mt-0.5">FH Aachen University · {{ language === 'de' ? 'Deutschland' : 'Germany' }}</p>
                  </div>
                  <span class="text-xs text-gray-400 font-medium shrink-0">{{ language === 'de' ? 'Mrz 2022 – Dez 2023' : 'Mar 2022 – Dec 2023' }}</span>
                </div>

                <ul class="space-y-2">
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'DT Workshops' : 'DT workshops' }}</strong> — {{ language === 'de' ? 'Studierende & Lehrende; Problem-Framing vor Loesungssuche' : 'students & faculty; problem framing before solutioning' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'HCD Methodik' : 'HCD methodology' }}</strong> — {{ language === 'de' ? 'Ingenieur-Curriculum; menschzentrierte Designprozesse' : 'engineering curriculum; human-centered design' }}</li>
                  <li class="role-bullet"><strong class="role-kw">{{ language === 'de' ? 'Curriculum' : 'Curriculum' }}</strong> — {{ language === 'de' ? 'Lernmaterialien & Kursgestaltung' : 'instructional materials & course design' }}</li>
                </ul>

                <div class="flex flex-wrap gap-2 mt-4">
                  <span class="tag">Design Thinking</span>
                  <span class="tag">{{ language === 'de' ? 'Bildung' : 'Education' }}</span>
                  <span class="tag">Facilitation</span>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>

    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue';

defineProps({ language: { type: String, default: 'en' } });

const el0 = ref(null);
const el1 = ref(null);
const el2 = ref(null);

onMounted(() => {
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.1 });

  [el0.value, el1.value, el2.value].forEach(el => { if (el) observer.observe(el); });
});
</script>

<style scoped>
.role-entry {
  position: relative;
  opacity: 0;
  transform: translateY(20px);
  transition: opacity 0.5s ease, transform 0.5s ease;
}

.role-entry.visible {
  opacity: 1;
  transform: none;
}

.role-bullet {
  font-size: 0.82rem;
  color: #4b5563;
  line-height: 1.5;
  padding-left: 0.75rem;
  position: relative;
}

.role-bullet::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0.5em;
  width: 4px;
  height: 4px;
  border-radius: 50%;
  background: #14b8a6;
}

.role-kw {
  color: #0f766e;
  font-weight: 700;
  font-size: 0.82rem;
}

.tag {
  font-size: 0.68rem;
  font-weight: 600;
  color: #0f766e;
  background: #f0fdfa;
  border: 1px solid #99f6e4;
  border-radius: 9999px;
  padding: 0.15rem 0.6rem;
}
</style>

// src/components/Experience.jsx
import { Reveal, Stagger, StaggerItem } from './motion/primitives';

const roles = [
  {
    id: 0,
    current: true,
    title: { en: 'Ecosystem & Product Builder', de: 'Ecosystem & Product Builder' },
    org: 'growthepie / orbal GmbH',
    location: { en: 'Remote', de: 'Remote' },
    dates: { en: 'Aug 2024 – Jun 2028', de: 'Aug 2024 – Jun 2026' },
    bullets: [
      {
        kw: { en: 'AI labeling agent, and RL pipelines', de: 'KI Labeling Agent' },
        detail: { en: '€1→€0.01/label, 4h→10min (100×)', de: '€1→€0,01/Label, 4h→10min (100×)' },
      },
      {
        kw: { en: 'AI sales engine for research backed outreach and lead tracking', de: 'KI Sales Engine' },
        detail: { en: '30 simultaneous conversations, 1h→10min per contact', de: '30 simultane Gespräche, 1h→10min pro Kontakt' },
      },
      {
        kw: { en: '3 grants secured and shipped · $50,000', de: '3 Grants · $50.000' },
        detail: { en: 'EF ESP DevTooling, Gitcoin GG25 OSS Developer Tooling & Infra, Arbitrum Questbook Dev Tooling', de: 'EF ESP DevTooling, Gitcoin GG25 OSS Developer Tooling & Infra, Arbitrum Questbook Dev Tooling' },
      },
      {
        kw: { en: 'Open Labels Initiative', de: 'Open Labels Initiative' },
        detail: { en: 'TypeScript SDK, Hardhat plugin, web frontend; adopted by Blockscout, Enscribe, Sourcify', de: 'TypeScript SDK, Hardhat Plugin, Web-Frontend; adoptiert von Blockscout, Enscribe, Sourcify' },
      },
      {
        kw: { en: 'L2 ecosystem research', de: 'L2 Ecosystem Research' },
        detail: { en: 'metrics & insights; protocols & data teams', de: 'Metriken & Insights; Protokolle & Daten-Teams' },
      },
      {
        kw: { en: 'Frontend development and tools integrations', de: 'Frontend' },
        detail: { en: 'Turned hard dev tasks into intuitive user input agentic flows', de: 'Forschung in Produkt-Interfaces überführt' },
      },
      {
        kw: { en: 'Internal AI advocate', de: 'KI Advocate' },
        detail: { en: 'tools, workflows & agents across engineering, research, product', de: 'Tools, Workflows & Agenten: Engineering, Research, Produkt' },
      },
    ],
    tags: [
      { en: 'TypeScript', de: 'TypeScript' },
      { en: 'Blockchain', de: 'Blockchain' },
      { en: 'AI Agents', de: 'KI Agenten' },
      { en: 'Grants', de: 'Grants' },
      { en: 'Open Source', de: 'Open Source' },
      { en: 'Product', de: 'Produkt' },
    ],
  },
  {
    id: 1,
    current: false,
    title: { en: 'Community & Growth Manager', de: 'Community & Growth Manager' },
    org: 'growthepie',
    location: { en: 'Remote', de: 'Remote' },
    dates: { en: 'Jun 2023 – Jul 2024', de: 'Jun 2023 – Jul 2024' },
    bullets: [
      {
        kw: { en: 'Community management', de: 'Community Management' },
        detail: { en: 'Web3 developers & researchers; blockchain analytics awareness', de: 'Web3-Entwickler & Researcher; Blockchain-Analytics-Awareness' },
      },
      {
        kw: { en: 'Content strategy', de: 'Content Strategie' },
        detail: { en: 'on-chain data translated into accessible narratives', de: 'On-Chain-Daten in zugängliche Narrative übersetzt' },
      },
      {
        kw: { en: 'Sales & partnerships', de: 'Sales & Partnerschaften' },
        detail: { en: 'protocol relationships; contribution to growth engine', de: 'Protokoll-Beziehungen; Beitrag zur Wachstums-Engine' },
      },
    ],
    tags: [
      { en: 'Community', de: 'Community' },
      { en: 'Content Strategy', de: 'Content Strategie' },
      { en: 'Web3', de: 'Web3' },
      { en: 'Sales', de: 'Sales' },
    ],
  },
  {
    id: 2,
    current: false,
    title: { en: 'Design Thinking Coach & Student Assistant', de: 'Design Thinking Coach & Studentische Hilfskraft' },
    org: 'FH Aachen University',
    location: { en: 'Germany', de: 'Deutschland' },
    dates: { en: 'Mar 2022 – Dec 2023', de: 'Mrz 2022 – Dez 2023' },
    bullets: [
      {
        kw: { en: 'DT workshops', de: 'DT Workshops' },
        detail: { en: 'students & faculty; problem framing before solutioning', de: 'Studierende & Lehrende; Problem-Framing vor Lösungssuche' },
      },
      {
        kw: { en: 'HCD methodology', de: 'HCD Methodik' },
        detail: { en: 'engineering curriculum; human-centered design', de: 'Ingenieur-Curriculum; menschzentrierte Designprozesse' },
      },
      {
        kw: { en: 'Curriculum', de: 'Curriculum' },
        detail: { en: 'instructional materials & course design', de: 'Lernmaterialien & Kursgestaltung' },
      },
    ],
    tags: [
      { en: 'Design Thinking', de: 'Design Thinking' },
      { en: 'Education', de: 'Bildung' },
      { en: 'Facilitation', de: 'Facilitation' },
    ],
  },
];

export default function Experience({ language }) {
  return (
    <section id="experience" className="relative overflow-hidden py-24 md:py-32 px-6 bg-neutral-50">
      {/* shared ambient paper texture, rotated so it reads fresh */}
      <div className="pointer-events-none absolute inset-0" aria-hidden="true">
        <img
          src="/images/generated/services-bg.jpg"
          alt=""
          className="absolute inset-0 w-full h-full object-cover opacity-40 rotate-180"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-neutral-50/80 via-transparent to-neutral-50" />
      </div>

      <div className="relative z-10 max-w-6xl mx-auto">

        {/* Section header */}
        <Reveal className="flex flex-col md:flex-row md:justify-between md:items-end mb-16">
          <div>
            <h2 className="font-display text-3xl md:text-4xl font-semibold tracking-tight text-ink">
              {language === 'de' ? 'Berufserfahrung' : 'Professional Experience'}
            </h2>
            <div className="w-16 h-1 bg-primary mt-3 rounded-full"></div>
          </div>
          <p className="text-sm text-neutral-500 mt-4 md:mt-0 md:text-right font-medium tracking-wide">
            {language === 'de' ? 'LÜCKEN IDENTIFIZIERT. SYSTEME GEBAUT. ERGEBNISSE GELIEFERT.' : 'GAPS IDENTIFIED. SYSTEMS BUILT. RESULTS SHIPPED.'}
          </p>
        </Reveal>

        {/* Timeline */}
        <div className="relative max-w-4xl mx-auto">
          {/* Vertical rail (md+) */}
          <div className="hidden md:block absolute left-5 top-2 bottom-2 w-px bg-neutral-200"></div>

          <Stagger className="space-y-10">
            {roles.map((role) => (
              <StaggerItem key={role.id} className="relative md:pl-16">
                {/* Marker (md+) */}
                <div
                  className={`hidden md:flex absolute left-0 top-6 w-10 h-10 rounded-full items-center justify-center z-10 ${role.current ? 'bg-primary shadow-sm shadow-primary/30' : 'bg-white border-2 border-neutral-300'
                    }`}
                >
                  <span
                    className={`rounded-full ${role.current ? 'w-2.5 h-2.5 bg-white' : 'w-2 h-2 bg-neutral-400'}`}
                  ></span>
                </div>

                {/* Card */}
                <div className="bg-white rounded-2xl border border-neutral-200 p-6 md:p-8 hover:shadow-md transition-shadow duration-200">
                  <div className="flex flex-wrap items-start justify-between gap-3 mb-4">
                    <div>
                      <h3 className="font-display text-xl font-semibold text-ink">{role.title[language]}</h3>
                      <p className="text-sm text-neutral-500 mt-1">{role.org} · {role.location[language]}</p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      {role.current && (
                        <span className="flex items-center gap-1.5 text-xs font-semibold text-primary bg-primary/10 border border-primary/20 px-3 py-1 rounded-full">
                          <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
                          {language === 'de' ? 'Aktuell' : 'Current'}
                        </span>
                      )}
                      <span className="text-xs text-neutral-500 font-medium">{role.dates[language]}</span>
                    </div>
                  </div>

                  <ul className="space-y-2.5">
                    {role.bullets.map((bullet, i) => (
                      <li key={i} className="flex gap-3 text-sm text-neutral-700 leading-relaxed">
                        <span className="mt-2 w-1 h-1 rounded-full bg-accent shrink-0"></span>
                        <span><strong className="text-ink font-semibold">{bullet.kw[language]}</strong> — {bullet.detail[language]}</span>
                      </li>
                    ))}
                  </ul>

                  <div className="flex flex-wrap gap-2 mt-5">
                    {role.tags.map((tag) => (
                      <span key={tag.en} className="text-xs font-medium text-neutral-600 bg-neutral-100 border border-neutral-200 rounded-full px-2.5 py-1">
                        {tag[language]}
                      </span>
                    ))}
                  </div>
                </div>
              </StaggerItem>
            ))}
          </Stagger>
        </div>

      </div>
    </section>
  );
}
