// src/components/Footer.jsx
import { Linkedin, Instagram, Twitter, Send } from 'lucide-react'
import { Reveal } from './motion/primitives'

const socials = [
  { name: 'LinkedIn', href: 'https://www.linkedin.com/in/ahoura-azarbin-a3887b180', icon: Linkedin },
  { name: 'X / Twitter', href: 'https://x.com/ahoura_az', icon: Twitter },
  { name: 'Instagram', href: 'https://instagram.com/ahouraazarbin', icon: Instagram },
  { name: 'Telegram', href: 'https://t.me/AghostraA', icon: Send },
]

export default function Footer({ language = 'en' }) {
  const year = new Date().getFullYear()

  const links = [
    { label: language === 'de' ? 'Leistungen' : 'Services', href: '#services' },
    { label: language === 'de' ? 'Arbeiten' : 'Work', href: '#projects' },
    { label: language === 'de' ? 'Erfahrung' : 'Experience', href: '#experience' },
    { label: language === 'de' ? 'Kontakt' : 'Contact', href: '#contact' },
  ]

  return (
    <footer className="bg-ink text-white pt-12 pb-8 px-6">
      <Reveal className="max-w-6xl mx-auto">
        <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-8 pb-8 border-b border-white/10">
          {/* Identity */}
          <div className="max-w-sm">
            <p className="font-display text-lg font-semibold text-white mb-1">Ahoura Azarbin</p>
            <p className="text-sm text-neutral-400 leading-relaxed">
              {language === 'de'
                ? 'AI Automation & Software Studio — agentische Automatisierung, RAG und Effizienz für kleine Teams.'
                : 'AI Automation & Software Studio — agentic automation, RAG, and efficiency for small teams.'}
            </p>
          </div>

          {/* Quick links */}
          <nav aria-label={language === 'de' ? 'Schnellzugriff' : 'Quick links'}>
            <ul className="flex flex-wrap gap-x-6 gap-y-2 text-sm">
              {links.map((link) => (
                <li key={link.href}>
                  <a
                    href={link.href}
                    className="text-neutral-400 transition-colors duration-150 hover:text-primary"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          {/* Socials */}
          <div className="flex gap-3">
            {socials.map((social) => {
              const Icon = social.icon
              return (
                <a
                  key={social.name}
                  href={social.href}
                  target="_blank"
                  rel="noopener"
                  aria-label={social.name}
                  className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-white/15 text-neutral-400 transition-colors duration-150 hover:border-primary hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"
                >
                  <Icon className="h-4 w-4" strokeWidth={1.75} />
                </a>
              )
            })}
          </div>
        </div>

        <div className="pt-6 flex flex-col sm:flex-row items-center justify-between gap-2 text-sm text-neutral-500">
          <p>© {year} Ahoura Azarbin. {language === 'de' ? 'Alle Rechte vorbehalten.' : 'All rights reserved.'}</p>
          <a href="mailto:ahouraazarbin@gmail.com" className="hover:text-primary transition-colors duration-150">
            ahouraazarbin@gmail.com
          </a>
        </div>
      </Reveal>
    </footer>
  )
}

// src/components/Footer.vue
<template>
  <footer class="bg-gradient-to-r from-gray-900 via-indigo-950 to-gray-900 text-white pt-16 pb-8 px-6">
    <div class="container mx-auto">
      <!-- Top section with main content -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 mb-12">
        <!-- About -->
        <div>
          <h3 class="text-2xl font-bold mb-4 text-white flex items-center">
            <span class="bg-gradient-to-r from-indigo-500 to-purple-500 bg-clip-text text-transparent">Ahoura Azarbin</span>
          </h3>
          <p class="text-gray-400 leading-relaxed mb-4">
            {{ language === 'de'
              ? 'Researcher mit Fokus auf Web3, Blockchain-Technologien und Datenanalyse mit Schwerpunkt Smart-Contract-Labeling.'
              : 'Researcher specializing in Web3, blockchain technologies, and data analytics with a focus on smart contract labeling.' }}
          </p>
          <p class="text-gray-400">
            {{ language === 'de' ? 'Standort: Aachen, Nordrhein-Westfalen, Deutschland' : 'Based in Aachen, North Rhine-Westphalia, Germany' }}
          </p>
        </div>
        
        <!-- Quick links -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-white">{{ language === 'de' ? 'Schnellzugriff' : 'Quick Links' }}</h3>
          <ul class="space-y-2">
            <li>
              <a href="#" class="text-gray-400 hover:text-indigo-400 transition-colors flex items-center">
                <svg class="w-3 h-3 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                {{ language === 'de' ? 'Start' : 'Home' }}
              </a>
            </li>
            <li>
              <a href="#experience" class="text-gray-400 hover:text-indigo-400 transition-colors flex items-center">
                <svg class="w-3 h-3 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                {{ language === 'de' ? 'Erfahrung' : 'Experience' }}
              </a>
            </li>
            <li>
              <a href="#projects" class="text-gray-400 hover:text-indigo-400 transition-colors flex items-center">
                <svg class="w-3 h-3 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                {{ language === 'de' ? 'Projekte' : 'Projects' }}
              </a>
            </li>
            <li>
              <a href="#skills" class="text-gray-400 hover:text-indigo-400 transition-colors flex items-center">
                <svg class="w-3 h-3 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
                {{ language === 'de' ? 'Faehigkeiten' : 'Skills' }}
              </a>
            </li>
          </ul>
        </div>
        
        <!-- Contact -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-white">{{ language === 'de' ? 'Kontakt' : 'Contact' }}</h3>
          <ul class="space-y-3">
            <li class="flex items-center text-gray-400">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2 text-indigo-400">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
              </svg>
              ahouraazarbin@gmail.com
            </li>
          </ul>
        </div>
        
        <!-- Social -->
        <div>
          <h3 class="text-lg font-semibold mb-4 text-white">{{ language === 'de' ? 'Folge mir' : 'Follow Me' }}</h3>
          <div class="flex space-x-4">
            <a href="https://instagram.com/ahouraazarbin" target="_blank" class="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center text-indigo-400 hover:bg-indigo-600 hover:text-white transition-colors">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd"></path>
              </svg>
            </a>
            <a href="https://x.com/ahoura_az" target="_blank" class="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center text-indigo-400 hover:bg-indigo-600 hover:text-white transition-colors">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"></path>
              </svg>
            </a>
            <a href="https://t.me/AghostraA" target="_blank" class="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center text-indigo-400 hover:bg-indigo-600 hover:text-white transition-colors">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.306.02.472-.18 1.898-.96 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/>
              </svg>
            </a>
            <a href="https://www.linkedin.com/in/ahoura-azarbin-a3887b180" target="_blank" class="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center text-indigo-400 hover:bg-indigo-600 hover:text-white transition-colors">
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fill-rule="evenodd" d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" clip-rule="evenodd"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      
      <!-- Bottom section with copyright -->
      <div class="pt-8 mt-8 border-t border-gray-800 text-center">
        <p class="text-gray-400">© {{ new Date().getFullYear() }} Ahoura Azarbin. {{ language === 'de' ? 'Alle Rechte vorbehalten.' : 'All Rights Reserved.' }}</p>
        <p class="text-gray-600 text-sm mt-2">{{ language === 'de' ? 'Erstellt mit Vue.js und Tailwind CSS' : 'Built with Vue.js and Tailwind CSS' }}</p>
      </div>
    </div>
  </footer>
</template>

<script setup>
defineProps({
  language: {
    type: String,
    default: 'en'
  }
});
</script>
