// src/components/ProjectCard.jsx
import { useState } from 'react'
import { AnimatePresence } from 'motion/react'
import { Trophy, Check, ChevronDown, Github, ArrowUpRight } from 'lucide-react'
import { motion, Pressable, EASE, useReducedMotion } from './motion/primitives'

export default function ProjectCard({
  title,
  category = '',
  tagline = '',
  description,
  fullDescription = '',
  technologies = [],
  features = [],
  bgImage = '',
  bgVideo = '',
  liveLink = '',
  codeLink = '',
  icon: Icon = null,
  featured = false,
  language = 'en',
}) {
  const [expanded, setExpanded] = useState(false)
  const reduce = useReducedMotion()
  const hasCaseStudy = Boolean(fullDescription || (features && features.length))

  return (
    <motion.article
      layout
      className={`project-card group relative flex flex-col overflow-hidden rounded-2xl border border-neutral-200 bg-white transition-shadow duration-200 hover:shadow-lg ${featured ? 'lg:grid lg:grid-cols-5 lg:items-stretch' : ''}`}
    >
      {/* Image */}
      {bgImage ? (
        <div
          className={`relative overflow-hidden bg-neutral-100 ${featured ? 'h-56 lg:h-auto lg:col-span-2' : 'h-44'}`}
        >
          <img
            src={bgImage}
            alt={title}
            loading="lazy"
            className="h-full w-full object-cover grayscale-[15%] transition-all duration-300 ease-out group-hover:grayscale-0 group-hover:scale-[1.03]"
          />
          {/* ambient loop for the featured card; the still above serves reduced-motion users */}
          {bgVideo && !reduce ? (
            <video
              src={bgVideo}
              poster={bgImage}
              autoPlay
              muted
              loop
              playsInline
              preload="metadata"
              aria-hidden="true"
              className="absolute inset-0 h-full w-full object-cover"
            />
          ) : null}
          <div className="absolute inset-0 bg-gradient-to-t from-neutral-900/10 to-transparent"></div>
        </div>
      ) : null}

      {/* Content */}
      <div className={`flex flex-1 flex-col ${featured ? 'p-6 md:p-8 lg:p-10 lg:col-span-3' : 'p-6 md:p-8'}`}>
        {/* Eyebrow: category */}
        <div className="mb-3 flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-neutral-500">
          {Icon ? <Icon size={14} className="text-neutral-400" /> : null}
          {category}
        </div>

        {/* Title */}
        <h3
          className={`font-display font-semibold tracking-tight text-neutral-900 leading-snug ${featured ? 'text-2xl md:text-3xl mb-3' : 'text-xl mb-2'}`}
        >
          {title}
        </h3>

        {/* Meta line: achievement / outcome badge */}
        {tagline ? (
          <div
            className={`mb-4 inline-flex w-fit items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold ${featured ? 'bg-primary/10 text-primary' : 'bg-neutral-100 text-neutral-700'}`}
          >
            <Trophy size={13} />
            {tagline}
          </div>
        ) : null}

        {/* Body */}
        <p className={`text-base leading-relaxed text-neutral-600 ${featured ? '' : 'text-sm'}`}>
          {description}
        </p>

        {/* Expandable case study */}
        <AnimatePresence initial={false}>
          {expanded ? (
            <motion.div
              key="case-study"
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.35, ease: EASE }}
              className="overflow-hidden"
            >
              <div className="pt-4 border-t border-neutral-100 mt-4">
                <p className="text-sm leading-relaxed text-neutral-600 mb-4">{fullDescription}</p>
                <ul className="space-y-2">
                  {features.map((feature, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-neutral-600">
                      <Check size={15} className="mt-0.5 shrink-0 text-accent" />
                      <span>{feature}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.div>
          ) : null}
        </AnimatePresence>

        {hasCaseStudy ? (
          <button
            type="button"
            className="mt-4 inline-flex w-fit items-center gap-1 text-sm font-semibold text-neutral-700 transition-colors duration-150 hover:text-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary rounded"
            onClick={() => setExpanded((v) => !v)}
          >
            {expanded ? (language === 'de' ? 'Weniger' : 'Show less') : (language === 'de' ? 'Case Study lesen' : 'Read case study')}
            <ChevronDown size={15} className={`transition-transform duration-200 ${expanded ? 'rotate-180' : ''}`} />
          </button>
        ) : null}

        {/* Footer: tags + links */}
        <div className="mt-auto pt-6 flex flex-wrap items-end justify-between gap-4">
          <div className="flex flex-wrap gap-1.5">
            {technologies.map((tech, i) => (
              <span
                key={i}
                className="rounded-full border border-neutral-200 bg-neutral-50 px-2.5 py-1 text-xs font-medium text-neutral-600"
              >
                {tech}
              </span>
            ))}
          </div>

          <div className="flex items-center gap-4 shrink-0">
            {codeLink ? (
              <Pressable
                as="a"
                href={codeLink}
                target="_blank"
                rel="noopener"
                lift={1.05}
                className="inline-flex items-center gap-1.5 text-sm font-semibold text-neutral-600 transition-colors duration-150 hover:text-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary rounded"
              >
                <Github size={16} />
                {language === 'de' ? 'Code' : 'Code'}
              </Pressable>
            ) : null}
            {liveLink ? (
              <Pressable
                as="a"
                href={liveLink}
                target="_blank"
                rel="noopener"
                lift={1.05}
                className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary transition-colors duration-150 hover:text-primary-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary rounded"
              >
                {language === 'de' ? 'Live ansehen' : 'View live'}
                <ArrowUpRight size={16} className="transition-transform duration-150 group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
              </Pressable>
            ) : null}
          </div>
        </div>
      </div>
    </motion.article>
  )
}

// src/components/ProjectCard.vue
<template>
  <div
    ref="cardRoot"
    class="project-card relative overflow-hidden rounded-2xl shadow-md hover:shadow-lg transition-shadow duration-300 cursor-pointer"
    @click="toggleExpand"
  >
    <!-- Background image + gradient -->
    <div class="absolute inset-0 bg-gradient-to-br opacity-90" :class="gradientClasses"></div>
    <div class="absolute inset-0 bg-cover bg-center mix-blend-overlay" :style="{ backgroundImage: `url(${bgImage})` }"></div>

    <!-- Fixed-height collapsed section -->
    <div class="relative flex flex-col p-7 card-body">
      <!-- Tagline pill -->
      <div class="mb-3">
        <span class="inline-block bg-white/20 backdrop-blur-sm text-white text-xs font-semibold px-3 py-1 rounded-full tracking-wide">
          {{ tagline }}
        </span>
      </div>

      <h3 class="text-xl font-bold text-white mb-4 leading-snug line-clamp-2">{{ title }}</h3>

      <!-- Description box — fixed height so all cards align -->
      <div class="bg-white/10 backdrop-blur-sm p-5 rounded-xl border border-white/20 mb-5 flex-1 flex flex-col justify-between">
        <p class="text-white/90 text-sm leading-relaxed line-clamp-3">{{ description }}</p>

        <!-- Tech pills -->
        <div class="flex flex-wrap gap-2 mt-4">
          <span
            v-for="(tech, i) in technologies"
            :key="i"
            class="px-3 py-1 bg-white/20 backdrop-blur-sm text-white text-xs font-medium rounded-full border border-white/20"
          >
            {{ tech }}
          </span>
        </div>
      </div>

      <!-- Expanded detail panel -->
      <div
        class="expanded-panel overflow-hidden transition-all duration-500"
        :style="{ maxHeight: isExpanded ? expandedHeight + 'px' : '0', opacity: isExpanded ? 1 : 0 }"
      >
        <div ref="expandedContent" class="bg-white/10 backdrop-blur-sm rounded-xl border border-white/20 p-5 mb-5">
          <p class="text-white/90 text-sm leading-relaxed mb-4">{{ fullDescription }}</p>

          <ul class="space-y-2 mb-4">
            <li
              v-for="(feature, i) in features"
              :key="i"
              class="flex items-start gap-2 text-white/85 text-sm"
            >
              <svg class="w-4 h-4 mt-0.5 shrink-0 text-white/60" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
              </svg>
              {{ feature }}
            </li>
          </ul>

          <a
            v-if="codeLink"
            :href="codeLink"
            target="_blank"
            class="inline-flex items-center gap-1.5 text-xs font-semibold text-white bg-white/20 hover:bg-white/30 px-4 py-2 rounded-full border border-white/30 transition-colors"
            @click.stop
          >
            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
            </svg>
            {{ language === 'de' ? 'Code ansehen' : 'View Code' }}
          </a>
        </div>
      </div>

      <!-- Footer row -->
      <div class="flex items-center justify-between mt-auto" @click.stop>
        <div class="flex gap-2">
          <a
            v-if="liveLink"
            :href="liveLink"
            target="_blank"
            class="inline-flex items-center gap-1.5 text-xs font-semibold text-white bg-white/20 hover:bg-white/30 px-4 py-2 rounded-full border border-white/30 transition-colors"
          >
            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
            </svg>
            {{ language === 'de' ? 'Live' : 'Live' }}
          </a>
        </div>

        <button
          class="inline-flex items-center gap-1.5 text-xs font-semibold text-white bg-white/20 hover:bg-white/30 px-4 py-2 rounded-full border border-white/30 transition-colors"
          @click.stop="toggleExpand"
        >
          {{ isExpanded ? (language === 'de' ? 'Weniger' : 'Less') : (language === 'de' ? 'Details' : 'Details') }}
          <svg class="w-3.5 h-3.5 transition-transform duration-300" :class="{ 'rotate-180': isExpanded }" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch, nextTick } from 'vue';

const props = defineProps({
  title: { type: String, required: true },
  tagline: { type: String, required: true },
  description: { type: String, required: true },
  fullDescription: { type: String, required: true },
  technologies: { type: Array, default: () => [] },
  features: { type: Array, default: () => [] },
  bgImage: { type: String, default: '' },
  colorScheme: { type: String, default: 'blue' },
  liveLink: { type: String, default: '' },
  codeLink: { type: String, default: '' },
  isExpanded: { type: Boolean, default: false },
  language: { type: String, default: 'en' }
});

const emit = defineEmits(['toggle-expand']);
const expandedContent = ref(null);
const expandedHeight = ref(0);

const toggleExpand = () => emit('toggle-expand');

const updateHeight = () => {
  if (expandedContent.value) {
    expandedHeight.value = expandedContent.value.scrollHeight + 20;
  }
};

onMounted(() => {
  updateHeight();
  window.addEventListener('resize', updateHeight);
});

const cardRoot = ref(null);

watch(() => props.isExpanded, async (val) => {
  if (val) {
    await nextTick();
    updateHeight();
    // Scroll so the expanded card is comfortably in view
    setTimeout(() => {
      if (cardRoot.value) {
        const rect = cardRoot.value.getBoundingClientRect();
        const offset = 80; // account for any fixed header
        if (rect.top < offset || rect.bottom > window.innerHeight) {
          window.scrollTo({
            top: window.scrollY + rect.top - offset,
            behavior: 'smooth',
          });
        }
      }
    }, 50);
  }
});

const gradientClasses = computed(() => ({
  blue: 'from-blue-700 to-cyan-600',
  teal: 'from-teal-700 to-cyan-600',
  green: 'from-green-700 to-teal-600',
  purple: 'from-purple-700 to-indigo-600',
  amber: 'from-amber-600 to-orange-500',
}[props.colorScheme] || 'from-blue-700 to-cyan-600'));
</script>

<style scoped>
/* Fixed height for the collapsed portion so all cards are uniform */
.card-body {
  min-height: 300px;
}

.expanded-panel {
  transition: max-height 0.5s cubic-bezier(0.16, 1, 0.3, 1), opacity 0.4s ease;
}
</style>
