// src/components/Skills.jsx
import {
  Bot,
  Code2,
  Database,
  Blocks,
  Briefcase,
  Users,
} from 'lucide-react';
import { Reveal, Stagger, StaggerItem } from './motion/primitives';

const content = {
  en: {
    eyebrow: 'Skills & Expertise',
    heading: 'My technical toolbox',
    githubTitle: 'GitHub Activity',
    githubAlt: 'GitHub contributions calendar for Aghostraa',
    languagesTitle: 'Languages',
    groups: [
      {
        icon: Bot,
        title: 'AI, Agents & Automation',
        skills: ['AI Agents', 'RAG Pipelines', 'LLM Integration', 'Prompt Engineering', 'Workflow Automation', 'Anomaly Detection'],
      },
      {
        icon: Code2,
        title: 'Software Engineering',
        skills: ['TypeScript', 'JavaScript', 'Python', 'Node.js', 'React', 'Vue', 'REST APIs', 'SDK Development'],
      },
      {
        icon: Database,
        title: 'Data & Analytics',
        skills: ['SQL', 'Data Analysis', 'Growth Metrics', 'Data Pipelines', 'On-chain Research'],
      },
      {
        icon: Blocks,
        title: 'Web3 & Blockchain',
        skills: ['Ethereum', 'EVM', 'Smart Contracts', 'Layer 2 Analytics', 'DeFi', 'EAS'],
      },
      {
        icon: Briefcase,
        title: 'Business & Strategy',
        skills: ['Grants & Funding', 'Business Development', 'Partnerships', 'Content Strategy', 'Project Management'],
      },
      {
        icon: Users,
        title: 'Professional Skills',
        skills: ['Leadership', 'Research', 'Communication', 'Product & Design', 'Community Management'],
      },
    ],
    languages: [
      { name: 'English', level: 'Full Professional' },
      { name: 'Persian', level: 'Native' },
      { name: 'German', level: 'Professional Working' },
    ],
  },
  de: {
    eyebrow: 'Fähigkeiten & Expertise',
    heading: 'Mein technischer Werkzeugkasten',
    githubTitle: 'GitHub Aktivität',
    githubAlt: 'GitHub Beitragskalender für Aghostraa',
    languagesTitle: 'Sprachen',
    groups: [
      {
        icon: Bot,
        title: 'KI, Agenten & Automatisierung',
        skills: ['KI-Agenten', 'RAG-Pipelines', 'LLM-Integration', 'Prompt Engineering', 'Workflow-Automatisierung', 'Anomalieerkennung'],
      },
      {
        icon: Code2,
        title: 'Softwareentwicklung',
        skills: ['TypeScript', 'JavaScript', 'Python', 'Node.js', 'React', 'Vue', 'REST APIs', 'SDK-Entwicklung'],
      },
      {
        icon: Database,
        title: 'Daten & Analytics',
        skills: ['SQL', 'Datenanalyse', 'Growth Metrics', 'Datenpipelines', 'On-chain Research'],
      },
      {
        icon: Blocks,
        title: 'Web3 & Blockchain',
        skills: ['Ethereum', 'EVM', 'Smart Contracts', 'Layer-2-Analyse', 'DeFi', 'EAS'],
      },
      {
        icon: Briefcase,
        title: 'Business & Strategie',
        skills: ['Grants & Förderung', 'Business Development', 'Partnerschaften', 'Content-Strategie', 'Projektmanagement'],
      },
      {
        icon: Users,
        title: 'Überfachliche Kompetenzen',
        skills: ['Führung', 'Forschung', 'Kommunikation', 'Produkt & Design', 'Community Management'],
      },
    ],
    languages: [
      { name: 'Englisch', level: 'Verhandlungssicher' },
      { name: 'Persisch', level: 'Muttersprache' },
      { name: 'Deutsch', level: 'Berufsbezogen' },
    ],
  },
};

export default function Skills({ language }) {
  const c = language === 'de' ? content.de : content.en;

  return (
    <section id="skills" className="relative overflow-hidden py-24 md:py-32">
      {/* shared ambient paper texture, mirrored so it reads fresh */}
      <div className="pointer-events-none absolute inset-0" aria-hidden="true">
        <img
          src="/images/generated/services-bg.jpg"
          alt=""
          className="absolute inset-0 w-full h-full object-cover opacity-40 -scale-x-100"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-neutral-50/80 via-transparent to-neutral-50" />
      </div>

      <div className="relative z-10 max-w-6xl mx-auto px-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:justify-between md:items-end mb-16 gap-4">
          <Reveal as="div" y={20} once amount={0.2} className="max-w-2xl">
            <p className="text-sm font-semibold uppercase tracking-wide text-accent mb-3">
              {c.eyebrow}
            </p>
            <h2 className="text-3xl md:text-4xl font-display font-semibold tracking-tight text-neutral-900">
              {c.heading}
            </h2>
          </Reveal>
        </div>

        {/* GitHub activity */}
        <Reveal as="div" y={20} once amount={0.2} className="mb-16 rounded-xl border border-neutral-200 bg-white p-6 md:p-8">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-xl font-display font-semibold text-neutral-900">
              {c.githubTitle}
            </h3>
            <a
              href="https://github.com/Aghostraa"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm font-medium text-neutral-500 hover:text-primary transition-colors duration-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary rounded"
            >
              @Aghostraa
            </a>
          </div>
          <div className="overflow-x-auto">
            <a href="https://github.com/Aghostraa" target="_blank" rel="noopener noreferrer" className="block min-w-[760px]">
              <img
                src="https://ghchart.rshah.org/Aghostraa"
                alt={c.githubAlt}
                loading="lazy"
                className="w-full"
              />
            </a>
          </div>
        </Reveal>

        {/* Skill categories */}
        <Stagger className="grid md:grid-cols-2 gap-x-10 gap-y-12">
          {c.groups.map((group) => (
            <StaggerItem key={group.title} as="div" y={20}>
              <div className="flex items-center gap-2 mb-4">
                <group.icon className="h-5 w-5 text-neutral-500" strokeWidth={1.75} />
                <h3 className="text-sm font-semibold uppercase tracking-wide text-neutral-500">
                  {group.title}
                </h3>
              </div>
              <Stagger as="ul" stagger={0.02} className="flex flex-wrap gap-2">
                {group.skills.map((skill) => (
                  <StaggerItem
                    key={skill}
                    as="li"
                    y={8}
                    className="text-sm text-neutral-700 bg-neutral-100 border border-neutral-200 rounded-full px-3 py-1.5"
                  >
                    {skill}
                  </StaggerItem>
                ))}
              </Stagger>
            </StaggerItem>
          ))}
        </Stagger>

        {/* Languages */}
        <div className="mt-16 md:mt-20">
          <h3 className="text-sm font-semibold uppercase tracking-wide text-neutral-500 mb-6">
            {c.languagesTitle}
          </h3>
          <Stagger className="grid sm:grid-cols-3 gap-6">
            {c.languages.map((lang) => (
              <StaggerItem
                key={lang.name}
                as="div"
                y={20}
                className="rounded-xl border border-neutral-200 bg-white p-5"
              >
                <h4 className="text-base font-display font-semibold text-neutral-900">{lang.name}</h4>
                <p className="text-sm text-neutral-500">{lang.level}</p>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
      </div>
    </section>
  );
}

// src/components/Skills.vue
<template>
  <section id="skills" class="py-20 px-6 bg-gradient-to-br from-teal-50/60 via-white to-cyan-50/40">
    <div class="container mx-auto">
      <div class="flex flex-col md:flex-row md:justify-between md:items-end mb-12">
        <div>
          <h2 class="text-3xl font-bold mb-2 text-gray-800">{{ language === 'de' ? 'Faehigkeiten & Expertise' : 'Skills & Expertise' }}</h2>
          <div class="w-24 h-1 bg-teal-500"></div>
        </div>
        <p class="text-gray-500 mt-4 md:mt-0 md:text-right text-sm font-medium">
          {{ language === 'de' ? 'MEIN TECHNISCHER WERKZEUGKASTEN' : 'MY TECHNICAL TOOLBOX' }}
        </p>
      </div>

      <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow mb-10">
        <div class="flex justify-between items-center mb-4">
          <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'GitHub Aktivitaet' : 'GitHub Activity' }}</h3>
          <a
            href="https://github.com/Aghostraa"
            target="_blank"
            rel="noopener noreferrer"
            class="text-xs font-medium text-teal-600 hover:text-teal-800 transition-colors"
          >
            @Aghostraa
          </a>
        </div>

        <div class="overflow-x-auto">
          <a href="https://github.com/Aghostraa" target="_blank" rel="noopener noreferrer" class="block min-w-[760px]">
            <img
              src="https://ghchart.rshah.org/Aghostraa"
              :alt="language === 'de' ? 'GitHub Beitragskalender fuer Aghostraa' : 'GitHub contributions calendar for Aghostraa'"
              loading="lazy"
              class="w-full"
            />
          </a>
        </div>
      </div>
      
      <div class="grid md:grid-cols-2 gap-10">
        <!-- Technical Skills -->
        <div>
          <h3 class="text-xl font-bold text-gray-800 mb-6 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2 text-teal-600">
              <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 3v1.5M4.5 8.25H3m18 0h-1.5M4.5 12H3m18 0h-1.5m-15 3.75H3m18 0h-1.5M8.25 19.5V21M12 3v1.5m0 15V21m3.75-18v1.5m0 15V21m-9-1.5h10.5a2.25 2.25 0 002.25-2.25V6.75a2.25 2.25 0 00-2.25-2.25H6.75A2.25 2.25 0 004.5 6.75v10.5a2.25 2.25 0 002.25 2.25zm.75-12h9v9h-9v-9z" />
            </svg>
            {{ language === 'de' ? 'Technische Faehigkeiten' : 'Technical Skills' }}
          </h3>
          
          <div class="space-y-6">
            <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
              <div class="flex justify-between mb-2">
                <h4 class="font-semibold text-gray-800">Web3 & Blockchain</h4>
                <span class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-0.5 rounded-full">{{ language === 'de' ? 'Experte' : 'Expert' }}</span>
              </div>
              <div class="w-full bg-gray-200 rounded-full h-2.5 mb-4">
                <div class="bg-gradient-to-r from-teal-500 to-sky-500 h-2.5 rounded-full" style="width: 95%"></div>
              </div>
              
              <div class="flex flex-wrap gap-2">
                <div class="group">
                  <div class="bg-teal-500/10 hover:bg-teal-500/20 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full transition-colors cursor-default flex items-center">
                    <svg class="w-3 h-3 mr-1 text-teal-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    Ethereum
                  </div>
                </div>
                <div class="group">
                  <div class="bg-teal-500/10 hover:bg-teal-500/20 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full transition-colors cursor-default flex items-center">
                    <svg class="w-3 h-3 mr-1 text-teal-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    EVM
                  </div>
                </div>
                <div class="group">
                  <div class="bg-teal-500/10 hover:bg-teal-500/20 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full transition-colors cursor-default flex items-center">
                    <svg class="w-3 h-3 mr-1 text-teal-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    Smart Contracts
                  </div>
                </div>
                <div class="group">
                  <div class="bg-teal-500/10 hover:bg-teal-500/20 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full transition-colors cursor-default flex items-center">
                    <svg class="w-3 h-3 mr-1 text-teal-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    {{ language === 'de' ? 'Layer-2-Analyse' : 'Layer 2 Analytics' }}
                  </div>
                </div>
                <div class="group">
                  <div class="bg-teal-500/10 hover:bg-teal-500/20 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full transition-colors cursor-default flex items-center">
                    <svg class="w-3 h-3 mr-1 text-teal-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    DeFi
                  </div>
                </div>
                <div class="group">
                  <div class="bg-teal-500/10 hover:bg-teal-500/20 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full transition-colors cursor-default flex items-center">
                    <svg class="w-3 h-3 mr-1 text-teal-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    EAS
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
              <div class="flex justify-between mb-2">
                <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Entwicklung & Tooling' : 'Development & Tooling' }}</h4>
                <span class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-0.5 rounded-full">{{ language === 'de' ? 'Versiert' : 'Skilled' }}</span>
              </div>
              <div class="w-full bg-gray-200 rounded-full h-2.5 mb-4">
                <div class="bg-gradient-to-r from-teal-500 to-sky-500 h-2.5 rounded-full" style="width: 85%"></div>
              </div>

              <div class="flex flex-wrap gap-2">
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">TypeScript</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">JavaScript</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">Node.js</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">Hardhat</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">React</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'SDK-Entwicklung' : 'SDK Development' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">REST APIs</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'KI-Agenten' : 'AI Agents' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Browser-Extensions' : 'Browser Extensions' }}</div>
              </div>
            </div>

            <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
              <div class="flex justify-between mb-2">
                <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Daten & Analytics' : 'Data & Analytics' }}</h4>
                <span class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-0.5 rounded-full">{{ language === 'de' ? 'Fortgeschritten' : 'Proficient' }}</span>
              </div>
              <div class="w-full bg-gray-200 rounded-full h-2.5 mb-4">
                <div class="bg-gradient-to-r from-teal-500 to-sky-500 h-2.5 rounded-full" style="width: 90%"></div>
              </div>

              <div class="flex flex-wrap gap-2">
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">SQL</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Datenanalyse' : 'Data Analysis' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Growth Metrics' : 'Growth Metrics' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Blockchain-Datenpipelines' : 'Blockchain Data Pipelines' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'On-chain Research' : 'On-chain Research' }}</div>
              </div>
            </div>

            <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
              <div class="flex justify-between mb-2">
                <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Business & Strategie' : 'Business & Strategy' }}</h4>
                <span class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-0.5 rounded-full">{{ language === 'de' ? 'Versiert' : 'Skilled' }}</span>
              </div>
              <div class="w-full bg-gray-200 rounded-full h-2.5 mb-4">
                <div class="bg-gradient-to-r from-teal-500 to-sky-500 h-2.5 rounded-full" style="width: 80%"></div>
              </div>

              <div class="flex flex-wrap gap-2">
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Grants & Foerderung' : 'Grants & Funding' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Business Development' : 'Business Development' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Partnerschaften' : 'Partnerships' }}</div>
                <div class="bg-teal-500/10 border border-teal-300/40 text-teal-700 text-xs font-medium px-2.5 py-1.5 rounded-full">{{ language === 'de' ? 'Content-Strategie' : 'Content Strategy' }}</div>
              </div>
            </div>

          </div>
        </div>
        
        <!-- Soft Skills & Languages -->
        <div>
          <h3 class="text-xl font-bold text-gray-800 mb-6 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2 text-teal-600">
              <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
            </svg>
            {{ language === 'de' ? 'Ueberfachliche Kompetenzen' : 'Professional Skills' }}
          </h3>
          
          <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow mb-8">
            <div class="grid grid-cols-2 gap-4">
              <div class="bg-white/50 backdrop-blur-sm border border-teal-100/70 p-4 rounded-xl">
                <div class="flex items-center mb-2">
                  <div class="w-10 h-10 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-teal-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
                    </svg>
                  </div>
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Fuehrung' : 'Leadership' }}</h4>
                </div>
                <div class="ml-12">
                  <div class="w-full bg-white rounded-full h-1.5">
                    <div class="bg-teal-600 h-1.5 rounded-full" style="width: 95%"></div>
                  </div>
                </div>
              </div>
              
              <div class="bg-white/50 backdrop-blur-sm border border-teal-100/70 p-4 rounded-xl">
                <div class="flex items-center mb-2">
                  <div class="w-10 h-10 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-teal-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 001.5-.189m-1.5.189a6.01 6.01 0 01-1.5-.189m3.75 7.478a12.06 12.06 0 01-4.5 0m3.75 2.383a14.406 14.406 0 01-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 10-7.517 0c.85.493 1.509 1.333 1.509 2.316V18" />
                    </svg>
                  </div>
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Forschung' : 'Research' }}</h4>
                </div>
                <div class="ml-12">
                  <div class="w-full bg-white rounded-full h-1.5">
                    <div class="bg-teal-600 h-1.5 rounded-full" style="width: 90%"></div>
                  </div>
                </div>
              </div>
              
              <div class="bg-white/50 backdrop-blur-sm border border-teal-100/70 p-4 rounded-xl">
                <div class="flex items-center mb-2">
                  <div class="w-10 h-10 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-teal-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6 6.878V6a2.25 2.25 0 012.25-2.25h7.5A2.25 2.25 0 0118 6v.878m-12 0c.235-.083.487-.128.75-.128h10.5c.263 0 .515.045.75.128m-12 0A2.25 2.25 0 004.5 9v.878m13.5-3A2.25 2.25 0 0119.5 9v.878m0 0a2.246 2.246 0 00-.75-.128H5.25c-.263 0-.515.045-.75.128m15 0A2.25 2.25 0 0121 12v6a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 18v-6c0-.98.626-1.813 1.5-2.122" />
                    </svg>
                  </div>
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Projektmanagement' : 'Project Management' }}</h4>
                </div>
                <div class="ml-12">
                  <div class="w-full bg-white rounded-full h-1.5">
                    <div class="bg-teal-600 h-1.5 rounded-full" style="width: 85%"></div>
                  </div>
                </div>
              </div>
              
              <div class="bg-white/50 backdrop-blur-sm border border-teal-100/70 p-4 rounded-xl">
                <div class="flex items-center mb-2">
                  <div class="w-10 h-10 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-teal-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
                    </svg>
                  </div>
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Kommunikation' : 'Communication' }}</h4>
                </div>
                <div class="ml-12">
                  <div class="w-full bg-white rounded-full h-1.5">
                    <div class="bg-teal-600 h-1.5 rounded-full" style="width: 90%"></div>
                  </div>
                </div>
              </div>

              <div class="bg-white/50 backdrop-blur-sm border border-teal-100/70 p-4 rounded-xl">
                <div class="flex items-center mb-2">
                  <div class="w-10 h-10 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-teal-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M9.53 16.122a3 3 0 00-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 003.388-1.62m-5.043-.025a15.994 15.994 0 011.622-3.395m3.42 3.42a15.995 15.995 0 004.764-4.648l3.876-5.814a1.151 1.151 0 00-1.597-1.597L14.146 6.32a15.996 15.996 0 00-4.649 4.763m3.42 3.42a6.776 6.776 0 00-3.42-3.42" />
                    </svg>
                  </div>
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Produkt & Design' : 'Product & Design' }}</h4>
                </div>
                <div class="ml-12">
                  <div class="w-full bg-white rounded-full h-1.5">
                    <div class="bg-teal-600 h-1.5 rounded-full" style="width: 85%"></div>
                  </div>
                </div>
              </div>

              <div class="bg-white/50 backdrop-blur-sm border border-teal-100/70 p-4 rounded-xl">
                <div class="flex items-center mb-2">
                  <div class="w-10 h-10 rounded-full bg-teal-500/10 border border-teal-200/50 flex items-center justify-center mr-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-teal-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
                    </svg>
                  </div>
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Community Management' : 'Community Management' }}</h4>
                </div>
                <div class="ml-12">
                  <div class="w-full bg-white rounded-full h-1.5">
                    <div class="bg-teal-600 h-1.5 rounded-full" style="width: 95%"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <h3 class="text-xl font-bold text-gray-800 mb-6 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2 text-teal-600">
              <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 21l5.25-11.25L21 21m-9-3h7.5M3 5.621a48.474 48.474 0 016-.371m0 0c1.12 0 2.233.038 3.334.114M9 5.25V3m3.334 2.364C11.176 10.658 7.69 15.08 3 17.502m9.334-12.138c.896.061 1.785.147 2.666.257m-4.589 8.495a18.023 18.023 0 01-3.827-5.802" />
            </svg>
            {{ language === 'de' ? 'Sprachen' : 'Languages' }}
          </h3>
          
          <div class="bg-white/70 backdrop-blur-sm p-6 rounded-xl shadow-sm border border-white/60 hover:shadow-md transition-shadow">
            <div class="space-y-6">
              <div>
                <div class="flex justify-between items-center mb-2">
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Englisch' : 'English' }}</h4>
                  <span class="text-sm text-gray-500">{{ language === 'de' ? 'Verhandlungssicher' : 'Full Professional' }}</span>
                </div>
                <div class="flex space-x-1">
                  <div class="h-2 w-full bg-teal-600 rounded-l-full"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600 rounded-r-full"></div>
                </div>
              </div>
              
              <div>
                <div class="flex justify-between items-center mb-2">
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Persisch' : 'Persian' }}</h4>
                  <span class="text-sm text-gray-500">{{ language === 'de' ? 'Muttersprache' : 'Native' }}</span>
                </div>
                <div class="flex space-x-1">
                  <div class="h-2 w-full bg-teal-600 rounded-l-full"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600 rounded-r-full"></div>
                </div>
              </div>
              
              <div>
                <div class="flex justify-between items-center mb-2">
                  <h4 class="font-semibold text-gray-800">{{ language === 'de' ? 'Deutsch' : 'German' }}</h4>
                  <span class="text-sm text-gray-500">{{ language === 'de' ? 'Berufsbezogen' : 'Professional Working' }}</span>
                </div>
                <div class="flex space-x-1">
                  <div class="h-2 w-full bg-teal-600 rounded-l-full"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-teal-600"></div>
                  <div class="h-2 w-full bg-gray-200 rounded-r-full"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
defineProps({
  language: {
    type: String,
    default: 'en'
  }
});
</script>
