// src/components/Volunteer.vue
<template>
  <section id="volunteer" class="py-20 px-6 bg-gradient-to-br from-indigo-50 via-white to-indigo-50">
    <div class="container mx-auto">
      <div class="flex flex-col md:flex-row md:justify-between md:items-end mb-12">
        <div>
          <h2 class="text-3xl font-bold mb-2 text-gray-800">{{ language === 'de' ? 'Ehrenamt & Fuehrung' : 'Volunteer & Leadership' }}</h2>
          <div class="w-24 h-1 bg-green-500"></div>
        </div>
        <p class="text-gray-500 mt-4 md:mt-0 md:text-right text-sm font-medium">
          {{ language === 'de' ? 'FUEHRUNG IN DER BLOCKCHAIN-COMMUNITY' : 'LEADERSHIP IN THE BLOCKCHAIN COMMUNITY' }}
        </p>
      </div>
      
      <div class="grid md:grid-cols-2 gap-8">
        <!-- Position 1: Advisor -->
        <div class="group bg-white rounded-xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-100">
          <div class="h-3 bg-gradient-to-r from-green-400 to-emerald-500"></div>
          <div class="p-6">
            <div class="flex justify-between items-start mb-4">
              <div>
                <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Berater' : 'Advisor' }}</h3>
                <div class="text-lg text-green-600 font-medium">Aachen Blockchain Club e.V.</div>
              </div>
              <span class="bg-green-100 text-green-800 text-sm font-medium px-3 py-1 rounded-full">{{ language === 'de' ? 'Mrz 2025 - Heute' : 'Mar 2025 - Present' }}</span>
            </div>
            
            <p class="text-gray-700 mb-4">
              {{ language === 'de' ? 'Als Berater des Clubs unterstuetze ich das Executive Team strategisch, begleite neue Mitglieder und foerdere Blockchain-Bildungsinitiativen an der FH Aachen.' : 'As an advisor to the club, I provide strategic guidance to the executive team, mentor new members, and support blockchain education initiatives at FH Aachen.' }}
            </p>
            
            <div class="flex flex-wrap gap-2 mt-4">
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Mentoring' : 'Mentoring' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Strategische Planung' : 'Strategic Planning' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Blockchain Bildung' : 'Blockchain Education' }}</div>
            </div>
            
            <div class="mt-6 flex items-center text-sm text-gray-500">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 mr-1 text-green-500">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
              </svg>
              <span>{{ language === 'de' ? 'Wissenschafts- und Technologiesektor' : 'Science and Technology sector' }}</span>
            </div>
          </div>
        </div>
        
        <!-- Position 2: President -->
        <div class="group bg-white rounded-xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-100">
          <div class="h-3 bg-gradient-to-r from-green-400 to-emerald-500"></div>
          <div class="p-6">
            <div class="flex justify-between items-start mb-4">
              <div>
                <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Praesident' : 'President' }}</h3>
                <div class="text-lg text-green-600 font-medium">Aachen Blockchain Club e.V.</div>
              </div>
              <span class="bg-green-100 text-green-800 text-sm font-medium px-3 py-1 rounded-full">Jun 2024 - Mar 2025</span>
            </div>
            
            <p class="text-gray-700 mb-4">
              {{ language === 'de' ? 'Leitung des universitaeren Blockchain-Clubs, inklusive Organisation von Bildungs-Events, Workshops und Networking-Sessions zur Foerderung von Blockchain und Web3 auf dem Campus.' : 'Led the university blockchain club, organizing educational events, workshops, and networking sessions to promote blockchain technology and Web3 awareness on campus.' }}
            </p>
            
            <div class="flex flex-wrap gap-2 mt-4">
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Fuehrung' : 'Leadership' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Event-Management' : 'Event Management' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Bildung' : 'Education' }}</div>
            </div>
            
            <div class="mt-6 flex items-center text-sm text-gray-500">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 mr-1 text-green-500">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418" />
              </svg>
              <span>{{ language === 'de' ? 'Bildungssektor' : 'Education sector' }}</span>
            </div>
          </div>
        </div>
      
        <!-- Position 3: Vice President -->
        <div class="group bg-white rounded-xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-100">
          <div class="h-3 bg-gradient-to-r from-green-400 to-emerald-500"></div>
          <div class="p-6">
            <div class="flex justify-between items-start mb-4">
              <div>
                <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Vizepraesident' : 'Vice President' }}</h3>
                <div class="text-lg text-green-600 font-medium">Aachen Blockchain Club e.V.</div>
              </div>
              <span class="bg-green-100 text-green-800 text-sm font-medium px-3 py-1 rounded-full">{{ language === 'de' ? 'Dez 2023 - Jun 2024' : 'Dec 2023 - Jun 2024' }}</span>
            </div>
            
            <p class="text-gray-700 mb-4">
              {{ language === 'de' ? 'Unterstuetzung des Praesidenten in Administration und Betrieb mit Fokus auf Partnerschaften und Ausbau des Club-Netzwerks.' : "Supported the club president in administration and operations, while focusing on building relationships with industry partners and expanding the club's network." }}
            </p>
            
            <div class="flex flex-wrap gap-2 mt-4">
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Administration' : 'Administration' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Partnerschaften' : 'Partnership Building' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Netzwerken' : 'Networking' }}</div>
            </div>
            
            <div class="mt-6 flex items-center text-sm text-gray-500">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 mr-1 text-green-500">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
              </svg>
              <span>{{ language === 'de' ? 'Bildungssektor' : 'Education sector' }}</span>
            </div>
          </div>
        </div>
        
        <!-- Position 4: Board Member -->
        <div class="group bg-white rounded-xl overflow-hidden shadow-md hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-100">
          <div class="h-3 bg-gradient-to-r from-green-400 to-emerald-500"></div>
          <div class="p-6">
            <div class="flex justify-between items-start mb-4">
              <div>
                <h3 class="text-xl font-bold text-gray-800">{{ language === 'de' ? 'Vorstand Forschung und Lehre' : 'Board Member Research and Teaching' }}</h3>
                <div class="text-lg text-green-600 font-medium">Aachen Blockchain Club e.V.</div>
              </div>
              <span class="bg-green-100 text-green-800 text-sm font-medium px-3 py-1 rounded-full">{{ language === 'de' ? 'Nov 2022 - Dez 2023' : 'Nov 2022 - Dec 2023' }}</span>
            </div>
            
            <p class="text-gray-700 mb-4">
              {{ language === 'de' ? 'Entwicklung von Lehrinhalten und Forschungsinitiativen zu Blockchain-Technologien, Smart Contracts und dezentralen Anwendungen fuer Studierende.' : 'Developed educational curriculum and research initiatives focusing on blockchain technologies, smart contracts, and decentralized applications for university students.' }}
            </p>
            
            <div class="flex flex-wrap gap-2 mt-4">
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Curriculum-Entwicklung' : 'Curriculum Development' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Forschung' : 'Research' }}</div>
              <div class="bg-green-100 text-green-800 px-2.5 py-1 rounded-lg text-xs font-medium">{{ language === 'de' ? 'Lehre' : 'Teaching' }}</div>
            </div>
            
            <div class="mt-6 flex items-center text-sm text-gray-500">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 mr-1 text-green-500">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418" />
              </svg>
              <span>{{ language === 'de' ? 'Bildungssektor' : 'Education sector' }}</span>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Call to Action -->
      <div class="mt-12 bg-white p-8 rounded-xl shadow-md border border-gray-100 text-center">
        <h3 class="text-xl font-bold text-gray-800 mb-3">{{ language === 'de' ? 'Blockchain-Bildung voranbringen' : 'Facilitating Blockchain Education' }}</h3>
        <p class="text-gray-600 max-w-2xl mx-auto mb-6">
          {{ language === 'de'
            ? 'Durch meine Rollen im Aachen Blockchain Club foerdere ich das Verstaendnis und die Anwendung von Blockchain-Technologie bei Studierenden und Lehrenden der FH Aachen.'
            : "Through my leadership roles at Aachen Blockchain Club, I'm dedicated to fostering understanding and adoption of blockchain technology among students and faculty at FH Aachen University." }}
        </p>
        <a href="#contact" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-gradient-to-r from-green-500 to-emerald-600 rounded-lg hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-green-200 transition-all">
          {{ language === 'de' ? 'Kontakt' : 'Contact Me' }}
          <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
          </svg>
        </a>
      </div>
    </div>
  </section>
</template>

<script setup>
defineProps({
  language: {
    type: String,
    default: 'en'
  }
});
</script>

// src/components/Volunteer.jsx
import { Beaker, GraduationCap, ArrowRight } from 'lucide-react';
import { Reveal, Stagger, StaggerItem, Pressable } from './motion/primitives';

const roles = [
  {
    id: 0,
    title: { en: 'Advisor', de: 'Berater' },
    org: 'Aachen Blockchain Club e.V.',
    dates: { en: 'Mar 2025 - Jun 2028', de: 'Mrz 2025 - Jun 2026' },
    description: {
      en: 'As an advisor to the club, I provide strategic guidance to the executive team, mentor new members, and support blockchain education initiatives at FH Aachen.',
      de: 'Als Berater des Clubs unterstütze ich das Executive Team strategisch, begleite neue Mitglieder und fördere Blockchain-Bildungsinitiativen an der FH Aachen.',
    },
    tags: [
      { en: 'Mentoring', de: 'Mentoring' },
      { en: 'Strategic Planning', de: 'Strategische Planung' },
      { en: 'Blockchain Education', de: 'Blockchain Bildung' },
    ],
    icon: Beaker,
    sector: { en: 'Science and Technology sector', de: 'Wissenschafts- und Technologiesektor' },
  },
  {
    id: 1,
    title: { en: 'President', de: 'Präsident' },
    org: 'Aachen Blockchain Club e.V.',
    dates: { en: 'Jun 2024 - Mar 2025', de: 'Jun 2024 - Mrz 2025' },
    description: {
      en: 'Led the university blockchain club, organizing educational events, workshops, and networking sessions to promote blockchain technology and Web3 awareness on campus.',
      de: 'Leitung des universitären Blockchain-Clubs, inklusive Organisation von Bildungs-Events, Workshops und Networking-Sessions zur Förderung von Blockchain und Web3 auf dem Campus.',
    },
    tags: [
      { en: 'Leadership', de: 'Führung' },
      { en: 'Event Management', de: 'Event-Management' },
      { en: 'Education', de: 'Bildung' },
    ],
    icon: GraduationCap,
    sector: { en: 'Education sector', de: 'Bildungssektor' },
  },
  {
    id: 2,
    title: { en: 'Vice President', de: 'Vizepräsident' },
    org: 'Aachen Blockchain Club e.V.',
    dates: { en: 'Dec 2023 - Jun 2024', de: 'Dez 2023 - Jun 2024' },
    description: {
      en: "Supported the club president in administration and operations, while focusing on building relationships with industry partners and expanding the club's network.",
      de: 'Unterstützung des Präsidenten in Administration und Betrieb mit Fokus auf Partnerschaften und Ausbau des Club-Netzwerks.',
    },
    tags: [
      { en: 'Administration', de: 'Administration' },
      { en: 'Partnership Building', de: 'Partnerschaften' },
      { en: 'Networking', de: 'Netzwerken' },
    ],
    icon: Beaker,
    sector: { en: 'Education sector', de: 'Bildungssektor' },
  },
  {
    id: 3,
    title: { en: 'Board Member Research and Teaching', de: 'Vorstand Forschung und Lehre' },
    org: 'Aachen Blockchain Club e.V.',
    dates: { en: 'Nov 2022 - Dec 2023', de: 'Nov 2022 - Dez 2023' },
    description: {
      en: 'Developed educational curriculum and research initiatives focusing on blockchain technologies, smart contracts, and decentralized applications for university students.',
      de: 'Entwicklung von Lehrinhalten und Forschungsinitiativen zu Blockchain-Technologien, Smart Contracts und dezentralen Anwendungen für Studierende.',
    },
    tags: [
      { en: 'Curriculum Development', de: 'Curriculum-Entwicklung' },
      { en: 'Research', de: 'Forschung' },
      { en: 'Teaching', de: 'Lehre' },
    ],
    icon: GraduationCap,
    sector: { en: 'Education sector', de: 'Bildungssektor' },
  },
];

export default function Volunteer({ language }) {
  return (
    <section id="volunteer" className="py-24 md:py-32 px-6 bg-white">
      <div className="max-w-6xl mx-auto">
        <Reveal className="flex flex-col md:flex-row md:justify-between md:items-end mb-14">
          <div>
            <h2 className="font-display text-3xl md:text-4xl font-semibold tracking-tight text-ink">
              {language === 'de' ? 'Ehrenamt & Führung' : 'Volunteer & Leadership'}
            </h2>
            <div className="w-16 h-1 bg-primary mt-3 rounded-full"></div>
          </div>
          <p className="text-sm text-neutral-500 mt-4 md:mt-0 md:text-right font-medium tracking-wide">
            {language === 'de' ? 'FÜHRUNG IN DER BLOCKCHAIN-COMMUNITY' : 'LEADERSHIP IN THE BLOCKCHAIN COMMUNITY'}
          </p>
        </Reveal>

        <Stagger className="grid md:grid-cols-2 gap-5">
          {roles.map((role) => {
            const Icon = role.icon;
            return (
              <StaggerItem
                key={role.id}
                className="bg-neutral-50 rounded-xl border border-neutral-200 p-6 hover:shadow-sm transition-shadow duration-200"
              >
                <div className="flex justify-between items-start gap-3 mb-3">
                  <div>
                    <h3 className="text-lg font-semibold text-ink">{role.title[language]}</h3>
                    <div className="text-sm text-neutral-500 mt-0.5">{role.org}</div>
                  </div>
                  <span className="shrink-0 text-xs font-medium text-neutral-600 bg-neutral-100 border border-neutral-200 px-2.5 py-1 rounded-full">
                    {role.dates[language]}
                  </span>
                </div>

                <p className="text-sm text-neutral-700 leading-relaxed mb-4">
                  {role.description[language]}
                </p>

                <div className="flex flex-wrap gap-2 mb-4">
                  {role.tags.map((tag) => (
                    <span key={tag.en} className="text-xs font-medium text-neutral-600 bg-white border border-neutral-200 rounded-full px-2.5 py-1">
                      {tag[language]}
                    </span>
                  ))}
                </div>

                <div className="flex items-center text-sm text-neutral-500">
                  <Icon className="w-4 h-4 mr-1.5 text-accent" strokeWidth={1.5} />
                  <span>{role.sector[language]}</span>
                </div>
              </StaggerItem>
            );
          })}
        </Stagger>

        {/* Call to Action */}
        <Reveal className="mt-10 bg-neutral-50 border border-neutral-200 p-8 rounded-xl text-center">
          <h3 className="text-xl font-semibold text-ink mb-3">{language === 'de' ? 'Blockchain-Bildung voranbringen' : 'Facilitating Blockchain Education'}</h3>
          <p className="text-neutral-600 max-w-2xl mx-auto mb-6 text-sm leading-relaxed">
            {language === 'de'
              ? 'Durch meine Rollen im Aachen Blockchain Club fördere ich das Verständnis und die Anwendung von Blockchain-Technologie bei Studierenden und Lehrenden der FH Aachen.'
              : "Through my leadership roles at Aachen Blockchain Club, I'm dedicated to fostering understanding and adoption of blockchain technology among students and faculty at FH Aachen University."}
          </p>
          <Pressable
            as="a"
            href="#contact"
            className="inline-flex items-center px-5 py-2.5 text-sm font-medium text-primary-fg bg-primary rounded-full hover:bg-primary-hover focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary transition-colors"
          >
            {language === 'de' ? 'Kontakt' : 'Contact Me'}
            <ArrowRight className="w-3.5 h-3.5 ml-2" strokeWidth={2} />
          </Pressable>
        </Reveal>
      </div>
    </section>
  );
}
