// src/App.jsx
import { useState } from 'react'
import Header from './components/Header.jsx'
import Services from './components/Services.jsx'
import Projects from './components/Projects.jsx'
import Experience from './components/Experience.jsx'
import Volunteer from './components/Volunteer.jsx'
import Writing from './components/Writing.jsx'
import Education from './components/Education.jsx'
import Skills from './components/Skills.jsx'
import Contact from './components/Contact.jsx'
import Footer from './components/Footer.jsx'

export default function App() {
  const [language, setLanguage] = useState('en')

  return (
    <div className="min-h-screen font-sans antialiased bg-neutral-50 text-neutral-900">
      <Header language={language} onUpdateLanguage={setLanguage} />
      <Services language={language} />
      <Projects language={language} />
      <Experience language={language} />
      <Volunteer language={language} />
      <Writing language={language} />
      <Education language={language} />
      <Skills language={language} />
      <Contact language={language} />
      <Footer language={language} />
    </div>
  )
}

// src/App.vue
<script setup>
import { ref } from 'vue'
import Header from './components/Header.vue'
import Contact from './components/Contact.vue'
import Experience from './components/Experience.vue'
import Volunteer from './components/Volunteer.vue'
import Projects from './components/Projects.vue'
import Writing from './components/Writing.vue'
import Education from './components/Education.vue'
import Skills from './components/Skills.vue'
import Footer from './components/Footer.vue'

const language = ref('en')

const setLanguage = (lang) => {
  language.value = lang
}
</script>

<template>
  <div class="min-h-screen font-sans antialiased bg-gradient-to-br from-slate-50 to-cyan-50">
    <Header :language="language" @update-language="setLanguage" />
    <Projects :language="language" />
    <Experience :language="language" />
    <Volunteer :language="language" />
    <Writing :language="language" />
    <Education :language="language" />
    <Skills :language="language" />
    <Contact :language="language" />
    <Footer :language="language" />
  </div>
</template>

<style>
html {
  scroll-behavior: smooth;
}

body {
  font-family: 'DM Sans', 'Segoe UI', sans-serif;
}

h1, h2, h3, h4, h5, h6 {
  font-family: 'Outfit', 'DM Sans', sans-serif;
}

/* Any global styles if needed */
</style>
