// cv/src/App.vue
<script setup>
import Header from './components/Header.vue'
import Contact from './components/Contact.vue'
import Experience from './components/Experience.vue'
import Volunteer from './components/Volunteer.vue'
import Projects from './components/Projects.vue'
import Education from './components/Education.vue'
import Skills from './components/Skills.vue'
import Footer from './components/Footer.vue'
</script>

<template>
  <div class="min-h-screen font-sans antialiased bg-gradient-to-br from-gray-50 to-gray-100">
    <Header />
    <Contact />
    <Experience />
    <Volunteer />
    <Projects />
    <Education />
    <Skills />
    <Footer />
  </div>
</template>

<style>
html {
  scroll-behavior: smooth;
}

body {
  font-family: 'Inter', 'Segoe UI', Roboto, sans-serif;
}

/* Any global styles if needed */
</style>

// src/App.jsx
import { useState } from 'react'
import Header from './components/Header.jsx'
import Services from './components/Services.jsx'
import Projects from './components/Projects.jsx'
import Experience from './components/Experience.jsx'
import Volunteer from './components/Volunteer.jsx'
import Writing from './components/Writing.jsx'
import Education from './components/Education.jsx'
import Skills from './components/Skills.jsx'
import Contact from './components/Contact.jsx'
import Footer from './components/Footer.jsx'

export default function App() {
  const [language, setLanguage] = useState('en')

  return (
    <div className="min-h-screen font-sans antialiased bg-neutral-50 text-neutral-900">
      <Header language={language} onUpdateLanguage={setLanguage} />
      <Services language={language} />
      <Projects language={language} />
      <Experience language={language} />
      <Volunteer language={language} />
      <Writing language={language} />
      <Education language={language} />
      <Skills language={language} />
      <Contact language={language} />
      <Footer language={language} />
    </div>
  )
}
